### ISSUE TITLE
Sea Going Crazy When Changing Before Starting Game 

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#17] opened 2021-12-30 20:43 UTC
When changing the Sea Level Setting before starting the game, once you start the game the Waves are crazy.

Once in the game I try changing Sea Height to CALM and nothing changes.

**When I exited the game and restarted, Sea Height was CALM.  When I ran the game and set Sea Height to Light Air, got the same crazy waves.  Move back to CALM and it will go display calm seas**

![image](https://user-images.githubusercontent.com/13039522/147786739-dec4de1b-3319-44f4-81e9-acf9301aa8af.png)

![image](https://user-images.githubusercontent.com/13039522/147786781-00d544b1-0602-48cc-ac8c-24062fd9d248.png)

**Comment by nitroman123** [comment] 2021-12-31 03:03
Maybe you hit the Load Button cause there is a save that might saved the ocean waves , i will check this out

**Comment by nitroman123** [comment] 2021-12-31 03:48
I cant reproduce. I also change a components maybe its ok now

**Comment by jesawyers** [comment] 2022-01-02 15:25
You were correct.  After setting everything, I clicked on Load instead of Start and the crazy seas returned.

**Comment by nitroman123** [comment] 2022-01-03 17:20
Closing this for now i will reopen this problem persists

**Closed by nitroman123** 2022-01-03 17:20 UTC
