### ISSUE TITLE
Crazy Seas When Changing Weather

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#44] opened 2022-04-27 21:20 UTC
Change Weather to Cloudy 1 and I get this...

![image](https://user-images.githubusercontent.com/13039522/165633086-bc4e24f7-fbca-455a-836b-063e29328042.png)

**Comment by nitroman123** [comment] 2022-04-28 06:11
its by design to be like this

**Comment by jesawyers** [comment] 2022-04-28 20:37
So changing to Cloudy 1 will also change the Wind Intensity?

**Comment by nitroman123** [comment] 2022-04-28 20:46
Every weather has his own wind intensity

**Comment by jesawyers** [comment] 2022-06-18 16:47
Ok...But should I not be able to select Cloudy 1 and calm seas??

**Comment by nitroman123** [comment] 2022-06-20 16:56
yes kinda like a 2 way knife cause when the weather is stormy the sea must follow

**Comment by jesawyers** [comment] 2022-06-20 17:56
Ok...I see where you are going here.  But again, should I not be able to have calm seas with clouds?? 

Also, when selecting Cloudy 1, the wind intensity is set to Light Breeze.  The seas appear to be very intense for a light Breeze.

![image](https://user-images.githubusercontent.com/13039522/174656410-f914407e-4ba5-49d0-a063-7381ac59e7ca.png)

**Comment by jesawyers** [comment] 2022-06-20 18:01
I did another test with Cloudy 1.  Once I select Cloudy 1, I can change the Wind Intensity to Calm and the clouds are still there.

**So setting Cloudy 1 and Calm Seas is not an issue.**

**However**, it appears that when selecting Cloudy 1 which selects Light Breeze, the sea intensity is to large...I think?

**Comment by jesawyers** [comment] 2022-06-23 20:15
This is still an issue.  Shifting from Clear Sky to Cloudy I get this...

![image](https://user-images.githubusercontent.com/13039522/175391111-ad5a5965-d7a2-4c6a-a8b5-e273fe8cb1f5.png)

**Comment by jesawyers** [comment] 2022-06-23 20:26
Ok...this is complete.  I did not see the "Use Weather Preset Wind Intensity" check box.

**Comment by nitroman123** [comment] 2022-06-24 06:18
yes and its on the main screen too  , i can close this on

**Closed as completed by nitroman123** 2022-06-24 06:18 UTC
